// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using moreno.myrep.api.Data;

#nullable disable

namespace moreno.myrep.api.Migrations
{
    [DbContext(typeof(MyrepDbContext))]
    [Migration("20231206140919_MigMyRep")]
    partial class MigMyRep
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("moreno.myrep.api.Models.Apontamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiaTrabalhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Etapa")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiaTrabalhoId");

                    b.ToTable("Apontamento");
                });

            modelBuilder.Entity("moreno.myrep.api.Models.DiaTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDiaTrabalho")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaTrabalho");
                });

            modelBuilder.Entity("moreno.myrep.api.Models.MesTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consultoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InicioPeriodo")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrestadorServico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TerminoPeriodo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MesTrabalho");
                });

            modelBuilder.Entity("moreno.myrep.api.Models.Apontamento", b =>
                {
                    b.HasOne("moreno.myrep.api.Models.DiaTrabalho", "DiaTrabalho")
                        .WithMany()
                        .HasForeignKey("DiaTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaTrabalho");
                });
#pragma warning restore 612, 618
        }
    }
}
